### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by JerrySievert** [Jaffe-/lispc#1]
hi!  this is awesome, but was wondering if you could add a license to this?

I'd love to be able to use it for a quick demo, but am wary without a license being added.

thanks much!

**Comment by Jaffe-** [comment]
Hi, I added the license document.
Note that this is very buggy and experimental from what I remember. It is not intended to actually be used for anything useful.

**Comment by JerrySievert** [comment]
thanks!  much appreciated.

I don't expect it to not be buggy, and if I ever build what I'm building for real, I'll replace the interpreter with something more robust.

in the mean time, in my case it's meant as a quick demo that isn't specific to lisp, and I think this will work nicely for my very specific use case :)
